'use client';

import { useEffect, useState } from 'react';
import { createClient } from '@/lib/supabase-auth';
import { useRouter } from 'next/navigation';
import { MeetingService } from '@/lib/database';
import type { Meeting } from '@/lib/database.types';

export const dynamic = 'force-dynamic';

export default function Dashboard() {
  const [user, setUser] = useState<{ id: string; email?: string } | null>(null);
  const [meetings, setMeetings] = useState<Meeting[]>([]);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    const getUserAndMeetings = async () => {
      const supabase = createClient();
      const { data: { user } } = await supabase.auth.getUser();
      
      if (!user) {
        router.push('/login');
        return;
      }
      
      setUser(user);
      
      // Fetch real meetings from database
      try {
        const userMeetings = await MeetingService.getUserMeetings(user.id, 20);
        setMeetings(userMeetings || []);
      } catch (error) {
        console.error('Error loading meetings:', error);
        setMeetings([]);
      }
      
      setLoading(false);
    };

    getUserAndMeetings();
  }, [router]);

  const handleSignOut = async () => {
    const supabase = createClient();
    await supabase.auth.signOut();
    router.push('/');
  };

  const getMeetingStatus = (meeting: Meeting): 'upcoming' | 'completed' => {
    const meetingDate = new Date(meeting.date);
    const today = new Date();
    today.setHours(0, 0, 0, 0);
    return meetingDate >= today ? 'upcoming' : 'completed';
  };

  const formatAttendees = (attendees: string[] | null): string[] => {
    if (!attendees) return [];
    if (typeof attendees === 'string') return [attendees];
    return attendees;
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="flex justify-between items-center h-16">
            <div className="flex items-center">
              <h1 className="text-2xl font-bold text-gray-900">MeetingPrep AI</h1>
            </div>
            <div className="flex items-center space-x-4">
              <span className="text-gray-700">Welcome, {user?.email}</span>
              <button
                onClick={handleSignOut}
                className="bg-gray-100 hover:bg-gray-200 px-4 py-2 rounded-lg text-gray-700 transition-colors"
              >
                Sign Out
              </button>
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Welcome Section */}
        <div className="mb-8">
          <h2 className="text-3xl font-bold text-gray-900 mb-2">Dashboard</h2>
          <p className="text-gray-600">View your meeting briefs generated by the Chrome extension.</p>
        </div>

        {/* Meetings Grid */}
        {meetings.length > 0 && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {meetings.map((meeting) => {
              const status = getMeetingStatus(meeting);
              const attendees = formatAttendees(meeting.attendees);
              
              return (
                <div key={meeting.id} className="bg-white rounded-xl shadow-sm border border-gray-200 p-6 hover:shadow-md transition-shadow">
                  <div className="flex items-start justify-between mb-4">
                    <h3 className="text-lg font-semibold text-gray-900">{meeting.title}</h3>
                    <span className={`px-2 py-1 rounded-full text-xs font-medium ${
                      status === 'upcoming' 
                        ? 'bg-blue-100 text-blue-800' 
                        : 'bg-green-100 text-green-800'
                    }`}>
                      {status}
                    </span>
                  </div>
                  
                  <div className="space-y-2 mb-4">
                    <p className="text-sm text-gray-600">
                      <span className="font-medium">Date:</span> {new Date(meeting.date).toLocaleDateString()}
                    </p>
                    {meeting.time && (
                      <p className="text-sm text-gray-600">
                        <span className="font-medium">Time:</span> {meeting.time}
                      </p>
                    )}
                    {attendees.length > 0 && (
                      <p className="text-sm text-gray-600">
                        <span className="font-medium">Attendees:</span> {attendees.join(', ')}
                      </p>
                    )}
                  </div>

                  <div className="flex space-x-2">
                    <button 
                      onClick={() => router.push(`/dashboard/meeting/${meeting.id}`)}
                      className="flex-1 bg-blue-600 text-white px-4 py-2 rounded-lg text-sm font-medium hover:bg-blue-700 transition-colors"
                    >
                      View Details
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        )}

        {/* Empty State */}
        {meetings.length === 0 && (
          <div className="text-center py-12">
            <div className="w-24 h-24 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <svg className="w-12 h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">No meetings yet</h3>
            <p className="text-gray-600 max-w-md mx-auto">
              Use the Chrome extension to generate meeting briefs from your calendar. Your briefs will appear here.
            </p>
          </div>
        )}
      </main>
    </div>
  );
}
